pipeline {
    //agent {label 'host'}
    agent any

    tools {
        maven '390' 
        jdk 'jdk17'
    }
    options {
    	buildDiscarder(logRotator(numToKeepStr: '30', artifactNumToKeepStr: '30'))
    }

    // Global variables which are not changed by environments/branches
    environment {
        AWS_REGION = "ap-southeast-1"
        BUILDVERSION = sh(returnStdout: true, script: "echo `date +%Y%d%m%H%M%S`").trim()
        COMMITHASH = sh(returnStdout: true, script: "git rev-parse HEAD").trim()
//         DOCKERFILE_PATH = "dev/Dockerfile"
//         PROFILE = "default"
    }

    stages {
        // Variables which are changed by environments/branches
        stage('Environment') {
            steps {
                script {
                    EXISTTAG = sh(returnStdout: true, script: "git tag --points-at HEAD | awk NF").trim()
                    if (EXISTTAG) {
                        GITTAG = sh(returnStdout: true, script: "git describe --exact-match --abbrev=0").trim()
                        if  (GITTAG.contains("release-")) {
                            env.AWS_ECR = "750078108771.dkr.ecr.ap-southeast-1.amazonaws.com"
                            env.ENVIRONTMENT = "alpha"
                            env.DOCKERFILE_PATH = "alpha/Dockerfile"
                            env.FARGATE_SERVICE = "alpha-aladdin-user"
                            env.ECR_REPO = "alpha-aladdin-user"
                            env.BUCKET = "alpha-aladdin-codedeploy-config"
                            env.PROFILE= "default"
                        }
                    }
                    if  (env.BRANCH_NAME == "master") {
                            env.AWS_ECR = "750078108771.dkr.ecr.ap-southeast-1.amazonaws.com"
                            env.ENVIRONTMENT = "alpha"
                            env.DOCKERFILE_PATH = "dev/Dockerfile"
                            env.FARGATE_SERVICE = "dev-aladdin-user"
                            env.ECR_REPO = "dev-aladdin-user"
                            env.BUCKET = "dev-aladdin-codedeploy-config"
                            env.PROFILE= "default"
                    }

                    if (env.BRANCH_NAME == "develop_new") {
                        env.AWS_ECR = "235410405967.dkr.ecr.ap-southeast-1.amazonaws.com"
                        env.ENVIRONTMENT = "dev"
                        env.DOCKERFILE_PATH = "dev/Dockerfile"
                        env.FARGATE_SERVICE = "dev-aladdin-user"
                        env.ECR_REPO = "dev-aladdin-user"
                        env.BUCKET = "dev-aladdin-codedeploy-config"
                        env.PROFILE= "aladdin-dev"
                    }
                }
            }
        }

        // Configure stage
        stage ('Configure') {
            steps {
                echo 'AWS login in this step'
            }
        }

        // Build stage
        stage ('Build Image') {
            steps {
                sh """
                    cd ./csv.excel
                    ./gradlew build -x test
                    docker build -t aws_ecr/ecr_repo:${COMMITHASH} -f ./cicd/${DOCKERFILE_PATH} .
                    docker tag aws_ecr/ecr_repo:${COMMITHASH} aws_ecr/ecr_repo:${BUILDVERSION}
                """
            }
        }

        // Create Deployment
        stage('Create Deployment') {
            steps {
                sh """
                    sed -i "s|IMAGE_NAME|${AWS_ECR}/${ECR_REPO}:${COMMITHASH}|g" ./cicd/${env.ENVIRONTMENT}/task-definition.json
                    aws --profile ${PROFILE} ecs register-task-definition \
                        --cli-input-json file://cicd/${env.ENVIRONTMENT}/task-definition.json \
                        --region ${AWS_REGION}
                    aws --profile ${PROFILE} s3 cp cicd/${env.ENVIRONTMENT}/appspec.yaml s3://${BUCKET}/${env.FARGATE_SERVICE}/appspec.yaml
                """

                retry(5) {
                    sh """
                        aws --profile ${PROFILE} deploy create-deployment \
                            --cli-input-json file://cicd/${env.ENVIRONTMENT}/deployment.json \
                            --region ${AWS_REGION} || { sleep 60 && exit 1; }
                    """
                }
            }
        }
    }

    post {
        always { 
            cleanWs()
            echo 'I will always say Hello again!'
            sh """
                docker rmi -f c32c84814084 c32c84814084 e9f851989d99
            """
        }
    }
}


